### PR TITLE
Add clear and backspace buttons

### PR DESCRIPTION
**Pull request by faillock**
Made with <3 by [richiesuper](https://github.com/richiesuper).

### CODE REVIEW

**Comment by faillock** [comment]
@ChristopherJ123 merge this pr

**Comment by faillock** [comment]
<@470579342657716224> @ChristopherJ123 helloooo

**Comment by faillock** [comment]
<@475170407943634964> <@979852186836164619> <@470579342657716224> bruh pada ngerjain tugas normalisasi database bjir

**Comment by faillock** [comment]
<@475170407943634964> <@979852186836164619> <@470579342657716224> good luck on your assignments hehe :thumbsup:

**Review by ChristopherJ123 — APPROVED** [review]
lgtm!

**Comment by ChristopherJ123** [comment]
Yeah you can stop abusing discord comments xd

**Comment by faillock** [comment]
@ChristopherJ123 <@470579342657716224> Well, it was to get your attention to merge this commit lol.

**Pull request merged**
